name: Deploy to Firebase (Test & Production)

on:
  push:
    branches:
      - test
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          
      - name: Debug environment variables
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}"

      - name: Install Dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" > "${{ github.workspace }}/firebase-key.json"

      - name: Build Project
        run: npm run build

      - name: Select Firebase Project and Deploy
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="${{ github.workspace }}/firebase-key.json"
          if [ "${{ github.ref_name }}" == "main" ]; then
            firebase use prod
          else
            firebase use test
          fi
          firebase deploy --only hosting