name: Deploy Nuxt SSR to Firebase (Test & Production)

on:
  push:
    branches:
      - main  # Despliegue a producción
      - test  # Despliegue a test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar Node.js con una versión compatible
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm install

      # 4. Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Construir el proyecto Nuxt.js
      - name: Build Nuxt.js project
        run: npm run build

      # 6. Desplegar a Firebase Functions (según la rama)
      - name: Deploy to Firebase Functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            firebase deploy --only functions --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
          elif [ "${GITHUB_REF##*/}" = "test" ]; then
            firebase deploy --only functions --token "${{ secrets.FIREBASE_DEPLOY_TOKEN }}"
          fi
